---
- name: Starting Splunk
  hosts: all
  become: yes
  become_user: splunk
  tasks:
    - name: task1
      shell: /opt/splunk/bin/splunk start

- name: Status Splunk
  hosts: all
  become: yes
  become_user: splunk
  tasks:
    - name: task2
      shell: /opt/splunk/bin/splunk status
      ignore_errors: yes